name: unsikuy_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  _fe_analyzer_shared: ^34.0.0
  dio: ^4.0.0
  equatable: ^2.0.3
  freezed: ^1.1.1
  get_storage: ^2.0.2
  json_annotation: ^4.0.1
  json_serializable: ^6.1.4
  logger: any
  path_provider: ^2.0.2
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  sizer: ^2.0.13
  flutter_form_builder: ^7.0.0
  image_picker: ^0.8.3+2
  modal_bottom_sheet: ^2.0.0
  permission_handler: ^8.3.0
  flutter_native_splash: ^2.2.8
  device_preview: any
  form_builder_validators: ^8.3.0
  cloud_firestore: 4.3.0
  firebase_core: 2.4.0
  firebase_auth: 4.2.3
  firebase_storage: 11.0.9
  uuid: 3.0.7
  intl: ^0.17.0
  lottie: 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  build_runner: any
  flutter_gen_runner: any
  flutter_launcher_icons: ^0.11.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - lib/app/resources/images/
  fonts: 
    - family: Lato
      fonts: 
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Bold.ttf
  uses-material-design: true

