// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSiN5CRA0ZMjQW1JyvMxFedLc9q7YuCzQ',
    appId: '1:597615739121:web:927e9f37437206fc0e2950',
    messagingSenderId: '597615739121',
    projectId: 'unsika-connect',
    authDomain: 'unsika-connect.firebaseapp.com',
    storageBucket: 'unsika-connect.appspot.com',
    measurementId: 'G-F3XL1S8VQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNXAkajvd2vOSGLFVWOWQXRH220etxx50',
    appId: '1:597615739121:android:c20b3b1312d4211d0e2950',
    messagingSenderId: '597615739121',
    projectId: 'unsika-connect',
    storageBucket: 'unsika-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzy20LZpjmLtFJtc-jD9IRVFfFlZbpD9s',
    appId: '1:597615739121:ios:ee84a291d10487f40e2950',
    messagingSenderId: '597615739121',
    projectId: 'unsika-connect',
    storageBucket: 'unsika-connect.appspot.com',
    iosClientId: '597615739121-9p029kk6ovtjnt68h3r8l4ffv4vkhfjr.apps.googleusercontent.com',
    iosBundleId: 'com.unsikuyapps.unsikuyApp',
  );
}
